spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      name: neo-config
      profile: dev
      label: master
      discovery:
        enabled: true
        serviceId: spring-cloud-config-server
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.17.197
    port: 10093
    username: admin
    password: 123456
server:
  port: 8009
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
