spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      name: neo-config
      profile: dev
      label: master
      discovery:
        enabled: true
        serviceId: spring-cloud-config-server
server:
  port: 8009
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
