spring:
  application:
    name: spring-cloud-consumer
  zipkin:
    base-url: http://192.168.17.197:10099
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
feign:
  hystrix:
    enabled: true
