server:
  port: 8008
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujunjie1992/spring-cloud-demo/config-repo/
          search-paths: config-repo
          username: "liujunjie1992"
          password: "*************"