server:
  port: 8008
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujunjie1992/spring-cloud-demo/
          basedir: SpringCloudDemo/config-repo
          skipSslValidation: true
          username: "liujunjie1992"
          password: "*************"
  rabbitmq:
    host: 192.168.17.197
    port: 10093
    username: admin
    password: 123456
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/