server:
  port: 8008
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujunjie1992/spring-cloud-demo/
          basedir: SpringCloudDemo/config-repo
          skipSslValidation: true
          username: "liujunjie1992"
          password: "*************"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/